(let ((default-directory "~/.emacs.d/"))
      (normal-top-level-add-to-load-path '("."))
      (normal-top-level-add-subdirs-to-load-path))
(server-start)

(require 'package)
(add-to-list 'package-archives '("marmalade" . "http://marmalade-repo.org/packages/"))

(require 'my-colors)
(require 'my-moving)
(require 'my-env)
(require 'my-windows)
(require 'my-interaction)
(require 'my-custom)
(require 'my-languages)
(require 'my-vcs)
(require 'my-editing)
(require 'my-projects)

(cd "~/")
